spring.application.name=ClichePiggyBank
storage.user-file=users.json
storage.user-temp-file=users.json.tmp
storage.account-file=accounts.json
storage.account-temp-file=accounts.json.tmp
storage.sanction-file=sanctions.json
storage.sanction-temp-file=sanctions.json.tmp
server.port=9092